# -*- coding: utf-8 -*-
"""auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVIZHptMDQXB5Bmscsxpjwx2Mvo07w5K
"""

# In real use, store hashed passwords in a DB or .env; here is a simple dict for demo

users = {
    "admin@school.com": "admin123",  # example user
}

def verify_login(email, password):
    return users.get(email) == password