# -*- coding: utf-8 -*-
"""SchoolScore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEuX6GxhE_tjBninpCU-iIt8Any1DYWO
"""

import streamlit as st
import pandas as pd
from utils import calculate_total, calculate_grade
from auth import verify_login

st.set_page_config(page_title="SmartGrade NG", layout="centered")

def login():
    st.title("🔐 SmartGrade NG - Admin Login")
    email = st.text_input("Email")
    password = st.text_input("Password", type="password")
    if st.button("Login"):
        if verify_login(email, password):
            st.session_state["logged_in"] = True
            st.session_state["user_email"] = email
            st.success("Logged in successfully!")
        else:
            st.error("Invalid email or password")

def main_app():
    st.title("📊 SmartGrade NG - Student Result Calculator")

    uploaded_file = st.file_uploader("Upload CSV file with columns: StudentName, Assignment, Test, Exam", type="csv")

    if uploaded_file:
        df = pd.read_csv(uploaded_file)

        # Validate columns
        expected_cols = {"StudentName", "Assignment", "Test", "Exam"}
        if not expected_cols.issubset(df.columns):
            st.error(f"CSV must contain these columns: {expected_cols}")
            return

        df['Total'] = df.apply(lambda row: calculate_total(row['Assignment'], row['Test'], row['Exam']), axis=1)
        df['Grade'] = df['Total'].apply(calculate_grade)

        st.success("Results calculated successfully!")
        st.dataframe(df)

        csv = df.to_csv(index=False).encode('utf-8')
        st.download_button("📥 Download Results CSV", csv, "results.csv", "text/csv")

def logout():
    if st.button("Logout"):
        st.session_state["logged_in"] = False
        st.session_state["user_email"] = None
        st.experimental_rerun()

if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
    st.session_state["user_email"] = None

if st.session_state["logged_in"]:
    main_app()
    logout()
else:
    login()