# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PF3YdIm-dNE-QUpTVof1InmvlSoNh6f9
"""

def calculate_total(assignment, test, exam):
    # Weightage: 20% assignment, 30% test, 50% exam
    return assignment * 0.2 + test * 0.3 + exam * 0.5

def calculate_grade(score):
    if score >= 70:
        return "A"
    elif score >= 60:
        return "B"
    elif score >= 50:
        return "C"
    elif score >= 45:
        return "D"
    else:
        return "F"